-- ============================================================================
-- Seed: Keyframe Registry Animations
-- Date: 2026-06-08
-- Description: Seeds the keyframe_registry table with 10 reusable animation
--              templates. Each entry has pre-computed keyframe data at 30fps,
--              a properties array listing which transforms are animated, and a
--              params_hash computed via scripts/generate_seed_hashes.js.
--
-- Run AFTER: database/migrate_keyframe_system.sql
-- Hashes generated by: node scripts/generate_seed_hashes.js
-- ============================================================================

USE autocliper;

-- ─── 1. fade_in ─────────────────────────────────────────────────────────────
-- Simple opacity fade from 0 to 1 over 10 frames (0.33s at 30fps)
INSERT INTO keyframe_registry (name, description, category, fps, duration_frames, keyframes, properties, transform_origin, params_hash)
VALUES (
  'fade_in',
  'Simple opacity fade from transparent to fully visible over 0.33 seconds',
  'entrance',
  30,
  10,
  '[{"frame":0,"opacity":0,"scale":1,"x":0,"y":0,"rotation":0},{"frame":3,"opacity":0.3,"scale":1,"x":0,"y":0,"rotation":0},{"frame":6,"opacity":0.7,"scale":1,"x":0,"y":0,"rotation":0},{"frame":9,"opacity":1.0,"scale":1,"x":0,"y":0,"rotation":0}]',
  '["opacity"]',
  'center center',
  '4034be13904b64304bc2071f21a79cd837587a2202c8de832c9966dc6da03ac4'
);

-- ─── 2. scale_bounce ────────────────────────────────────────────────────────
-- Scale overshoots to 1.2, settles back through 0.9 and 1.05 to 1.0 with fade-in
INSERT INTO keyframe_registry (name, description, category, fps, duration_frames, keyframes, properties, transform_origin, params_hash)
VALUES (
  'scale_bounce',
  'Bouncy scale entrance: overshoots 1.2x then settles to 1.0 with opacity fade-in over 0.5 seconds',
  'entrance',
  30,
  15,
  '[{"frame":0,"opacity":0,"scale":0,"x":0,"y":0,"rotation":0},{"frame":4,"opacity":1,"scale":1.2,"x":0,"y":0,"rotation":0},{"frame":8,"opacity":1,"scale":0.9,"x":0,"y":0,"rotation":0},{"frame":11,"opacity":1,"scale":1.05,"x":0,"y":0,"rotation":0},{"frame":14,"opacity":1,"scale":1.0,"x":0,"y":0,"rotation":0}]',
  '["scale","opacity"]',
  'center center',
  'c7a0922b84dd4584f3dc17a4a712f2a95216ccab3f032c86520d41324758f215'
);

-- ─── 3. slide_up ────────────────────────────────────────────────────────────
-- Slides from 50px below to origin with opacity fade
INSERT INTO keyframe_registry (name, description, category, fps, duration_frames, keyframes, properties, transform_origin, params_hash)
VALUES (
  'slide_up',
  'Slides upward from 50px offset to origin with opacity fade over 0.4 seconds',
  'entrance',
  30,
  12,
  '[{"frame":0,"opacity":0,"scale":1,"x":0,"y":50,"rotation":0},{"frame":3,"opacity":0.4,"scale":1,"x":0,"y":35,"rotation":0},{"frame":6,"opacity":0.7,"scale":1,"x":0,"y":18,"rotation":0},{"frame":9,"opacity":0.9,"scale":1,"x":0,"y":5,"rotation":0},{"frame":11,"opacity":1.0,"scale":1,"x":0,"y":0,"rotation":0}]',
  '["y","opacity"]',
  'center center',
  '1bf560775ae3f47fb6451a10ba4297c871cbe769358593b2018f783795727a60'
);

-- ─── 4. slide_down ──────────────────────────────────────────────────────────
-- Slides from 50px above to origin with opacity fade
INSERT INTO keyframe_registry (name, description, category, fps, duration_frames, keyframes, properties, transform_origin, params_hash)
VALUES (
  'slide_down',
  'Slides downward from -50px offset to origin with opacity fade over 0.4 seconds',
  'entrance',
  30,
  12,
  '[{"frame":0,"opacity":0,"scale":1,"x":0,"y":-50,"rotation":0},{"frame":3,"opacity":0.4,"scale":1,"x":0,"y":-35,"rotation":0},{"frame":6,"opacity":0.7,"scale":1,"x":0,"y":-18,"rotation":0},{"frame":9,"opacity":0.9,"scale":1,"x":0,"y":-5,"rotation":0},{"frame":11,"opacity":1.0,"scale":1,"x":0,"y":0,"rotation":0}]',
  '["y","opacity"]',
  'center center',
  '9ce0e6516d3d0955769b8f6f17630254acdaad13b9c5d9388c9f2429b82d35c6'
);

-- ─── 5. slide_left ──────────────────────────────────────────────────────────
-- Slides from 50px right to origin with opacity fade
INSERT INTO keyframe_registry (name, description, category, fps, duration_frames, keyframes, properties, transform_origin, params_hash)
VALUES (
  'slide_left',
  'Slides leftward from 50px right offset to origin with opacity fade over 0.4 seconds',
  'entrance',
  30,
  12,
  '[{"frame":0,"opacity":0,"scale":1,"x":50,"y":0,"rotation":0},{"frame":3,"opacity":0.4,"scale":1,"x":35,"y":0,"rotation":0},{"frame":6,"opacity":0.7,"scale":1,"x":18,"y":0,"rotation":0},{"frame":9,"opacity":0.9,"scale":1,"x":5,"y":0,"rotation":0},{"frame":11,"opacity":1.0,"scale":1,"x":0,"y":0,"rotation":0}]',
  '["x","opacity"]',
  'center center',
  '32f74ea6405ab220b75d808c4985e4191a969cefaa903cceca9cba7c922bba51'
);

-- ─── 6. slide_right ─────────────────────────────────────────────────────────
-- Slides from 50px left to origin with opacity fade
INSERT INTO keyframe_registry (name, description, category, fps, duration_frames, keyframes, properties, transform_origin, params_hash)
VALUES (
  'slide_right',
  'Slides rightward from -50px left offset to origin with opacity fade over 0.4 seconds',
  'entrance',
  30,
  12,
  '[{"frame":0,"opacity":0,"scale":1,"x":-50,"y":0,"rotation":0},{"frame":3,"opacity":0.4,"scale":1,"x":-35,"y":0,"rotation":0},{"frame":6,"opacity":0.7,"scale":1,"x":-18,"y":0,"rotation":0},{"frame":9,"opacity":0.9,"scale":1,"x":-5,"y":0,"rotation":0},{"frame":11,"opacity":1.0,"scale":1,"x":0,"y":0,"rotation":0}]',
  '["x","opacity"]',
  'center center',
  'a1375023ea5e44d4da5e56ddbb4762c93bde3616b7a41742149a2eb135c1368f'
);

-- ─── 7. pop_in ──────────────────────────────────────────────────────────────
-- Pops in with scale overshoot to 1.3 then settles to 1.0
INSERT INTO keyframe_registry (name, description, category, fps, duration_frames, keyframes, properties, transform_origin, params_hash)
VALUES (
  'pop_in',
  'Quick pop entrance: scales from 0 to 1.3x overshoot then settles to 1.0 over 0.33 seconds',
  'entrance',
  30,
  10,
  '[{"frame":0,"opacity":0,"scale":0,"x":0,"y":0,"rotation":0},{"frame":3,"opacity":0.8,"scale":1.3,"x":0,"y":0,"rotation":0},{"frame":6,"opacity":1.0,"scale":0.95,"x":0,"y":0,"rotation":0},{"frame":9,"opacity":1.0,"scale":1.0,"x":0,"y":0,"rotation":0}]',
  '["scale","opacity"]',
  'center center',
  'ef590c5a52df16445949d8c20262541c870921e11161a41fc1f4eb874648302d'
);

-- ─── 8. slam_in ─────────────────────────────────────────────────────────────
-- Dramatic slam: starts at 3x scale, crashes down to 1.0 very quickly
INSERT INTO keyframe_registry (name, description, category, fps, duration_frames, keyframes, properties, transform_origin, params_hash)
VALUES (
  'slam_in',
  'Dramatic slam entrance: starts at 3x scale and slams down to 1.0 over 0.27 seconds',
  'entrance',
  30,
  8,
  '[{"frame":0,"opacity":0,"scale":3.0,"x":0,"y":0,"rotation":0},{"frame":2,"opacity":0.7,"scale":1.5,"x":0,"y":0,"rotation":0},{"frame":4,"opacity":1.0,"scale":0.95,"x":0,"y":0,"rotation":0},{"frame":6,"opacity":1.0,"scale":1.02,"x":0,"y":0,"rotation":0},{"frame":7,"opacity":1.0,"scale":1.0,"x":0,"y":0,"rotation":0}]',
  '["scale","opacity"]',
  'center center',
  '1f334bc35eca8ceb606bc53e52d67cc4926ba639412f6ca594c12d9f066ba070'
);

-- ─── 9. typewriter_reveal ───────────────────────────────────────────────────
-- Gradual opacity ramp with slight upward y movement, like text being typed
INSERT INTO keyframe_registry (name, description, category, fps, duration_frames, keyframes, properties, transform_origin, params_hash)
VALUES (
  'typewriter_reveal',
  'Gradual typewriter-style reveal with slow opacity ramp and subtle y drift over 0.67 seconds',
  'entrance',
  30,
  20,
  '[{"frame":0,"opacity":0,"scale":1,"x":0,"y":5,"rotation":0},{"frame":3,"opacity":0.15,"scale":1,"x":0,"y":4,"rotation":0},{"frame":6,"opacity":0.3,"scale":1,"x":0,"y":3,"rotation":0},{"frame":9,"opacity":0.5,"scale":1,"x":0,"y":2,"rotation":0},{"frame":12,"opacity":0.7,"scale":1,"x":0,"y":1,"rotation":0},{"frame":15,"opacity":0.85,"scale":1,"x":0,"y":0.5,"rotation":0},{"frame":19,"opacity":1.0,"scale":1,"x":0,"y":0,"rotation":0}]',
  '["opacity","y"]',
  'center center',
  'cd46b5aabb42efe2d54f32a65b5d8fa4c781b12506d3249fe6f4aa8cbd64e210'
);

-- ─── 10. pulse ──────────────────────────────────────────────────────────────
-- Loopable pulse: scale breathes between 1.0 and 1.1, returns to start
INSERT INTO keyframe_registry (name, description, category, fps, duration_frames, keyframes, properties, transform_origin, params_hash)
VALUES (
  'pulse',
  'Loopable pulse animation: scale breathes 1.0 to 1.1 and back over 0.5 seconds',
  'emphasis',
  30,
  15,
  '[{"frame":0,"opacity":1,"scale":1.0,"x":0,"y":0,"rotation":0},{"frame":4,"opacity":1,"scale":1.05,"x":0,"y":0,"rotation":0},{"frame":7,"opacity":1,"scale":1.1,"x":0,"y":0,"rotation":0},{"frame":11,"opacity":1,"scale":1.05,"x":0,"y":0,"rotation":0},{"frame":14,"opacity":1,"scale":1.0,"x":0,"y":0,"rotation":0}]',
  '["scale"]',
  'center center',
  '8f98c304aa54a6b50f009c215f01ae5fcac934353d97fa4501a24bfec066dca2'
);

-- ============================================================================
-- Seed: Caption Templates
-- Description: Seeds caption_templates with 10 entries across 4 categories
--              (viral, professional, cinematic, playful). 6 animated templates
--              reference keyframe_registry IDs, 4 are static. Entry #3 is the
--              default (is_default=1). All are system presets (user_id=NULL).
-- ============================================================================

-- ─── 1. Neon Glow Bounce (viral, animated) ──────────────────────────────────
INSERT INTO caption_templates (name, description, category, thumbnail_url, style_type, config, user_id, is_active, is_default, sort_order)
VALUES (
  'Neon Glow Bounce',
  'Bold neon green text with glow shadow and scale bounce entrance — high energy viral look',
  'viral',
  NULL,
  'animated',
  '{
    "font": { "family": "Impact", "weight": "bold", "size": 72, "letter_spacing": 1.5, "line_height": 1.2, "text_transform": "uppercase" },
    "colors": { "primary": "#39FF14", "secondary": "#FFFFFF" },
    "highlight": { "color": "#FFFF00", "style": "glow", "transition": "bounce", "transition_duration_ms": 200 },
    "background": { "enabled": false, "color": "#000000", "opacity": 0.0, "padding_x": 0, "padding_y": 0, "border_radius": 0, "per_word": false },
    "outline": { "enabled": true, "color": "#000000", "width": 3 },
    "shadow": { "enabled": true, "color": "#39FF14", "blur": 15, "offset_x": 0, "offset_y": 0 },
    "position": { "anchor": "bottom", "y_offset": -120, "safe_area": { "top_percent": 10, "bottom_percent": 20, "side_percent": 10 } },
    "display": { "max_lines": 2, "max_line_width_percent": 85.0, "overflow_behavior": "wrap", "words_per_segment": 5 },
    "animation": { "entrance_keyframe_id": 2, "exit_keyframe_id": null, "highlight_keyframe_id": 10, "transform_origin": "center center" }
  }',
  NULL,
  1,
  0,
  10
);

-- ─── 2. Bold Yellow Slam (viral, animated) ──────────────────────────────────
INSERT INTO caption_templates (name, description, category, thumbnail_url, style_type, config, user_id, is_active, is_default, sort_order)
VALUES (
  'Bold Yellow Slam',
  'Dramatic yellow text with heavy black outline and slam entrance — maximum impact',
  'viral',
  NULL,
  'animated',
  '{
    "font": { "family": "Arial Black", "weight": "900", "size": 80, "letter_spacing": 2.0, "line_height": 1.1, "text_transform": "uppercase" },
    "colors": { "primary": "#FFD700", "secondary": "#FF4500" },
    "highlight": { "color": "#FF0000", "style": "scale", "transition": "bounce", "transition_duration_ms": 150 },
    "background": { "enabled": false, "color": "#000000", "opacity": 0.0, "padding_x": 0, "padding_y": 0, "border_radius": 0, "per_word": false },
    "outline": { "enabled": true, "color": "#000000", "width": 4 },
    "shadow": { "enabled": true, "color": "#000000", "blur": 8, "offset_x": 3, "offset_y": 3 },
    "position": { "anchor": "center", "y_offset": 50, "safe_area": { "top_percent": 10, "bottom_percent": 20, "side_percent": 10 } },
    "display": { "max_lines": 2, "max_line_width_percent": 90.0, "overflow_behavior": "scale_down", "words_per_segment": 4 },
    "animation": { "entrance_keyframe_id": 8, "exit_keyframe_id": null, "highlight_keyframe_id": null, "transform_origin": "center center" }
  }',
  NULL,
  1,
  0,
  20
);

-- ─── 3. Minimal White Fade (professional, animated) — DEFAULT ───────────────
INSERT INTO caption_templates (name, description, category, thumbnail_url, style_type, config, user_id, is_active, is_default, sort_order)
VALUES (
  'Minimal White Fade',
  'Clean white text with subtle fade-in entrance and smooth highlight — professional default',
  'professional',
  NULL,
  'animated',
  '{
    "font": { "family": "Helvetica", "weight": "500", "size": 54, "letter_spacing": 0.5, "line_height": 1.4, "text_transform": "none" },
    "colors": { "primary": "#FFFFFF", "secondary": "#CCCCCC" },
    "highlight": { "color": "#4FC3F7", "style": "color", "transition": "smooth", "transition_duration_ms": 300 },
    "background": { "enabled": true, "color": "#000000", "opacity": 0.5, "padding_x": 12, "padding_y": 6, "border_radius": 6, "per_word": false },
    "outline": { "enabled": false, "color": "#000000", "width": 0 },
    "shadow": { "enabled": true, "color": "#000000", "blur": 4, "offset_x": 0, "offset_y": 2 },
    "position": { "anchor": "bottom", "y_offset": -100, "safe_area": { "top_percent": 10, "bottom_percent": 20, "side_percent": 10 } },
    "display": { "max_lines": 2, "max_line_width_percent": 80.0, "overflow_behavior": "wrap", "words_per_segment": 5 },
    "animation": { "entrance_keyframe_id": 1, "exit_keyframe_id": null, "highlight_keyframe_id": null, "transform_origin": "center center" }
  }',
  NULL,
  1,
  1,
  30
);

-- ─── 4. Corporate Blue Static (professional, static) ────────────────────────
INSERT INTO caption_templates (name, description, category, thumbnail_url, style_type, config, user_id, is_active, is_default, sort_order)
VALUES (
  'Corporate Blue Static',
  'Clean blue-and-white text with no animation — simple professional look for business content',
  'professional',
  NULL,
  'static',
  '{
    "font": { "family": "Arial", "weight": "600", "size": 48, "letter_spacing": 0.3, "line_height": 1.5, "text_transform": "none" },
    "colors": { "primary": "#FFFFFF", "secondary": "#B0BEC5" },
    "highlight": { "color": "#2196F3", "style": "background", "transition": "instant", "transition_duration_ms": 100 },
    "background": { "enabled": true, "color": "#1A237E", "opacity": 0.75, "padding_x": 16, "padding_y": 8, "border_radius": 4, "per_word": false },
    "outline": { "enabled": false, "color": "#000000", "width": 0 },
    "shadow": { "enabled": false, "color": "#000000", "blur": 0, "offset_x": 0, "offset_y": 0 },
    "position": { "anchor": "bottom", "y_offset": -80, "safe_area": { "top_percent": 10, "bottom_percent": 20, "side_percent": 10 } },
    "display": { "max_lines": 2, "max_line_width_percent": 75.0, "overflow_behavior": "wrap", "words_per_segment": 6 },
    "animation": { "entrance_keyframe_id": null, "exit_keyframe_id": null, "highlight_keyframe_id": null, "transform_origin": null }
  }',
  NULL,
  1,
  0,
  40
);

-- ─── 5. Cinematic Gold Slide (cinematic, animated) ──────────────────────────
INSERT INTO caption_templates (name, description, category, thumbnail_url, style_type, config, user_id, is_active, is_default, sort_order)
VALUES (
  'Cinematic Gold Slide',
  'Elegant gold text with dramatic shadow and smooth slide-up entrance — movie trailer feel',
  'cinematic',
  NULL,
  'animated',
  '{
    "font": { "family": "Georgia", "weight": "700", "size": 60, "letter_spacing": 1.0, "line_height": 1.3, "text_transform": "uppercase" },
    "colors": { "primary": "#FFD700", "secondary": "#FFF8E1" },
    "highlight": { "color": "#FFFFFF", "style": "color", "transition": "smooth", "transition_duration_ms": 400 },
    "background": { "enabled": false, "color": "#000000", "opacity": 0.0, "padding_x": 0, "padding_y": 0, "border_radius": 0, "per_word": false },
    "outline": { "enabled": true, "color": "#1A1A1A", "width": 2 },
    "shadow": { "enabled": true, "color": "#000000", "blur": 12, "offset_x": 2, "offset_y": 4 },
    "position": { "anchor": "bottom", "y_offset": -150, "safe_area": { "top_percent": 10, "bottom_percent": 20, "side_percent": 10 } },
    "display": { "max_lines": 2, "max_line_width_percent": 80.0, "overflow_behavior": "wrap", "words_per_segment": 5 },
    "animation": { "entrance_keyframe_id": 3, "exit_keyframe_id": null, "highlight_keyframe_id": null, "transform_origin": "bottom center" }
  }',
  NULL,
  1,
  0,
  50
);

-- ─── 6. Dark Cinematic Typewriter (cinematic, animated) ─────────────────────
INSERT INTO caption_templates (name, description, category, thumbnail_url, style_type, config, user_id, is_active, is_default, sort_order)
VALUES (
  'Dark Cinematic Typewriter',
  'White text on dark semi-transparent bar with typewriter reveal — documentary narration style',
  'cinematic',
  NULL,
  'animated',
  '{
    "font": { "family": "Courier New", "weight": "400", "size": 44, "letter_spacing": 0.8, "line_height": 1.6, "text_transform": "none" },
    "colors": { "primary": "#F5F5F5", "secondary": "#9E9E9E" },
    "highlight": { "color": "#FFB300", "style": "underline", "transition": "smooth", "transition_duration_ms": 350 },
    "background": { "enabled": true, "color": "#1B1B1B", "opacity": 0.85, "padding_x": 20, "padding_y": 10, "border_radius": 2, "per_word": false },
    "outline": { "enabled": false, "color": "#000000", "width": 0 },
    "shadow": { "enabled": false, "color": "#000000", "blur": 0, "offset_x": 0, "offset_y": 0 },
    "position": { "anchor": "bottom", "y_offset": -90, "safe_area": { "top_percent": 10, "bottom_percent": 20, "side_percent": 10 } },
    "display": { "max_lines": 2, "max_line_width_percent": 85.0, "overflow_behavior": "wrap", "words_per_segment": 6 },
    "animation": { "entrance_keyframe_id": 9, "exit_keyframe_id": null, "highlight_keyframe_id": null, "transform_origin": "center center" }
  }',
  NULL,
  1,
  0,
  60
);

-- ─── 7. Bubblegum Pop (playful, animated) ───────────────────────────────────
INSERT INTO caption_templates (name, description, category, thumbnail_url, style_type, config, user_id, is_active, is_default, sort_order)
VALUES (
  'Bubblegum Pop',
  'Bright pink text with playful pop-in entrance and bouncy word highlights — fun and energetic',
  'playful',
  NULL,
  'animated',
  '{
    "font": { "family": "Comic Sans MS", "weight": "bold", "size": 64, "letter_spacing": 0.5, "line_height": 1.3, "text_transform": "none" },
    "colors": { "primary": "#FF69B4", "secondary": "#FFE4E1" },
    "highlight": { "color": "#FF1493", "style": "background", "transition": "bounce", "transition_duration_ms": 250 },
    "background": { "enabled": true, "color": "#FFFFFF", "opacity": 0.9, "padding_x": 10, "padding_y": 5, "border_radius": 20, "per_word": true },
    "outline": { "enabled": true, "color": "#C2185B", "width": 2 },
    "shadow": { "enabled": true, "color": "#FF69B4", "blur": 10, "offset_x": 0, "offset_y": 0 },
    "position": { "anchor": "center", "y_offset": 30, "safe_area": { "top_percent": 10, "bottom_percent": 20, "side_percent": 10 } },
    "display": { "max_lines": 2, "max_line_width_percent": 80.0, "overflow_behavior": "wrap", "words_per_segment": 4 },
    "animation": { "entrance_keyframe_id": 7, "exit_keyframe_id": null, "highlight_keyframe_id": 10, "transform_origin": "center center" }
  }',
  NULL,
  1,
  0,
  70
);

-- ─── 8. Rainbow Slide Party (playful, static) ───────────────────────────────
INSERT INTO caption_templates (name, description, category, thumbnail_url, style_type, config, user_id, is_active, is_default, sort_order)
VALUES (
  'Rainbow Slide Party',
  'Colorful multi-tone text with rounded background pills per word — cheerful static style',
  'playful',
  NULL,
  'static',
  '{
    "font": { "family": "Verdana", "weight": "700", "size": 56, "letter_spacing": 0.3, "line_height": 1.4, "text_transform": "none" },
    "colors": { "primary": "#FFFFFF", "secondary": "#FFC107" },
    "highlight": { "color": "#E040FB", "style": "background", "transition": "instant", "transition_duration_ms": 100 },
    "background": { "enabled": true, "color": "#7C4DFF", "opacity": 0.85, "padding_x": 14, "padding_y": 6, "border_radius": 16, "per_word": true },
    "outline": { "enabled": false, "color": "#000000", "width": 0 },
    "shadow": { "enabled": true, "color": "#4A148C", "blur": 6, "offset_x": 0, "offset_y": 3 },
    "position": { "anchor": "bottom", "y_offset": -110, "safe_area": { "top_percent": 10, "bottom_percent": 20, "side_percent": 10 } },
    "display": { "max_lines": 2, "max_line_width_percent": 85.0, "overflow_behavior": "wrap", "words_per_segment": 4 },
    "animation": { "entrance_keyframe_id": null, "exit_keyframe_id": null, "highlight_keyframe_id": null, "transform_origin": null }
  }',
  NULL,
  1,
  0,
  80
);

-- ─── 9. Elegant Serif Quiet (professional, static) ──────────────────────────
INSERT INTO caption_templates (name, description, category, thumbnail_url, style_type, config, user_id, is_active, is_default, sort_order)
VALUES (
  'Elegant Serif Quiet',
  'Refined serif font with muted tones and no animation — understated elegance for interviews',
  'professional',
  NULL,
  'static',
  '{
    "font": { "family": "Times New Roman", "weight": "400", "size": 50, "letter_spacing": 0.2, "line_height": 1.5, "text_transform": "none" },
    "colors": { "primary": "#ECEFF1", "secondary": "#90A4AE" },
    "highlight": { "color": "#80CBC4", "style": "color", "transition": "smooth", "transition_duration_ms": 250 },
    "background": { "enabled": true, "color": "#263238", "opacity": 0.7, "padding_x": 14, "padding_y": 8, "border_radius": 3, "per_word": false },
    "outline": { "enabled": false, "color": "#000000", "width": 0 },
    "shadow": { "enabled": false, "color": "#000000", "blur": 0, "offset_x": 0, "offset_y": 0 },
    "position": { "anchor": "bottom", "y_offset": -95, "safe_area": { "top_percent": 10, "bottom_percent": 20, "side_percent": 10 } },
    "display": { "max_lines": 2, "max_line_width_percent": 75.0, "overflow_behavior": "wrap", "words_per_segment": 6 },
    "animation": { "entrance_keyframe_id": null, "exit_keyframe_id": null, "highlight_keyframe_id": null, "transform_origin": null }
  }',
  NULL,
  1,
  0,
  90
);

-- ─── 10. Fire Slide Left (viral, static) ────────────────────────────────────
INSERT INTO caption_templates (name, description, category, thumbnail_url, style_type, config, user_id, is_active, is_default, sort_order)
VALUES (
  'Fire Orange Static',
  'Bold orange text with thick black outline and no animation — punchy static look for short clips',
  'viral',
  NULL,
  'static',
  '{
    "font": { "family": "Impact", "weight": "bold", "size": 70, "letter_spacing": 1.0, "line_height": 1.2, "text_transform": "uppercase" },
    "colors": { "primary": "#FF6D00", "secondary": "#FFAB40" },
    "highlight": { "color": "#FFFFFF", "style": "color", "transition": "instant", "transition_duration_ms": 80 },
    "background": { "enabled": false, "color": "#000000", "opacity": 0.0, "padding_x": 0, "padding_y": 0, "border_radius": 0, "per_word": false },
    "outline": { "enabled": true, "color": "#000000", "width": 4 },
    "shadow": { "enabled": true, "color": "#BF360C", "blur": 6, "offset_x": 2, "offset_y": 2 },
    "position": { "anchor": "center", "y_offset": 40, "safe_area": { "top_percent": 10, "bottom_percent": 20, "side_percent": 10 } },
    "display": { "max_lines": 2, "max_line_width_percent": 90.0, "overflow_behavior": "scale_down", "words_per_segment": 4 },
    "animation": { "entrance_keyframe_id": null, "exit_keyframe_id": null, "highlight_keyframe_id": null, "transform_origin": null }
  }',
  NULL,
  1,
  0,
  100
);



-- ============================================================================
-- Seed: Hook Templates
-- Description: Seeds hook_templates with 8 entries across categories
--              (viral, professional, cinematic, playful). 6 animated templates
--              use per_line animation referencing keyframe_registry IDs with
--              staggered delays. 2 are static. 2 have decorations enabled
--              (badge/divider). All are system presets (user_id=NULL).
--              CRITICAL: effects.flash.enable=false, effects.particles.enable=false,
--              overlay.gradient_top.enable=false, overlay.gradient_bottom.enable=false
-- ============================================================================

-- ─── 1. Bold Impact Slide (viral, animated, 3 lines) ────────────────────────
INSERT INTO hook_templates (name, description, category, thumbnail_url, style_type, config, user_id, is_active, is_default, sort_order)
VALUES (
  'Bold Impact Slide',
  'High-energy 3-line hook with bold white text, per-line slide-up entrance with staggered delays',
  'viral',
  NULL,
  'animated',
  '{
    "text": {
      "lines": [
        { "font_family": null, "font_size": 64, "font_weight": "900", "color": "#FFFFFF", "letter_spacing": 1.5, "text_transform": "uppercase" },
        { "font_family": null, "font_size": 56, "font_weight": "bold", "color": "#FFD700", "letter_spacing": 1.0, "text_transform": "uppercase" },
        { "font_family": null, "font_size": 48, "font_weight": "bold", "color": "#FFFFFF", "letter_spacing": 0.5, "text_transform": "none" }
      ],
      "default_font": { "family": "Impact", "weight": "bold", "size": 56, "color": "#FFFFFF", "letter_spacing": 1.0 }
    },
    "box": { "enabled": true, "color": "#000000", "opacity": 0.6, "padding": 24, "border_radius": 0, "border_color": null, "border_width": 0 },
    "position": { "anchor": "center", "y_offset": -50, "x_offset": 0 },
    "animation": {
      "entrance_keyframe_id": 3,
      "transform_origin": "center center",
      "per_line": [
        { "keyframe_id": 3, "delay_ms": 0, "transform_origin": null },
        { "keyframe_id": 3, "delay_ms": 150, "transform_origin": null },
        { "keyframe_id": 3, "delay_ms": 300, "transform_origin": null }
      ]
    },
    "decorations": { "divider": { "enable": false }, "emoji_row": { "enable": false }, "badge": { "enable": false } },
    "effects": { "flash": { "enable": false }, "particles": { "enable": false } },
    "overlay": { "gradient_top": { "enable": false }, "gradient_bottom": { "enable": false } },
    "timing": { "display_duration_seconds": 3.5, "delay_before_seconds": 0.3 }
  }',
  NULL,
  1,
  0,
  10
);

-- ─── 2. Neon Pop Entrance (viral, animated, 3 lines, badge decoration) ──────
INSERT INTO hook_templates (name, description, category, thumbnail_url, style_type, config, user_id, is_active, is_default, sort_order)
VALUES (
  'Neon Pop Entrance',
  'Vibrant neon green hook with pop-in animation, staggered per-line delays, and "VIRAL" badge decoration',
  'viral',
  NULL,
  'animated',
  '{
    "text": {
      "lines": [
        { "font_family": "Arial Black", "font_size": 60, "font_weight": "900", "color": "#39FF14", "letter_spacing": 2.0, "text_transform": "uppercase" },
        { "font_family": null, "font_size": 52, "font_weight": "bold", "color": "#FFFFFF", "letter_spacing": 1.0, "text_transform": "uppercase" },
        { "font_family": null, "font_size": 44, "font_weight": "600", "color": "#39FF14", "letter_spacing": 0.5, "text_transform": "none" }
      ],
      "default_font": { "family": "Helvetica", "weight": "bold", "size": 52, "color": "#39FF14", "letter_spacing": 1.0 }
    },
    "box": { "enabled": true, "color": "#0D0D0D", "opacity": 0.85, "padding": 20, "border_radius": 8, "border_color": "#39FF14", "border_width": 2 },
    "position": { "anchor": "center", "y_offset": 0, "x_offset": 0 },
    "animation": {
      "entrance_keyframe_id": 7,
      "transform_origin": "center center",
      "per_line": [
        { "keyframe_id": 7, "delay_ms": 0, "transform_origin": null },
        { "keyframe_id": 7, "delay_ms": 200, "transform_origin": null },
        { "keyframe_id": 7, "delay_ms": 400, "transform_origin": null }
      ]
    },
    "decorations": { "divider": { "enable": false }, "emoji_row": { "enable": false }, "badge": { "enable": true, "text": "VIRAL", "bg_color": "#FF0000", "font_size": 18, "keyframe_id": 7 } },
    "effects": { "flash": { "enable": false }, "particles": { "enable": false } },
    "overlay": { "gradient_top": { "enable": false }, "gradient_bottom": { "enable": false } },
    "timing": { "display_duration_seconds": 4.0, "delay_before_seconds": 0.2 }
  }',
  NULL,
  1,
  0,
  20
);

-- ─── 3. Clean Corporate Fade (professional, animated, 2 lines) ──────────────
INSERT INTO hook_templates (name, description, category, thumbnail_url, style_type, config, user_id, is_active, is_default, sort_order)
VALUES (
  'Clean Corporate Fade',
  'Professional 2-line hook with subtle fade-in entrance and clean typography on semi-transparent dark background',
  'professional',
  NULL,
  'animated',
  '{
    "text": {
      "lines": [
        { "font_family": "Helvetica", "font_size": 52, "font_weight": "600", "color": "#FFFFFF", "letter_spacing": 0.5, "text_transform": "none" },
        { "font_family": null, "font_size": 40, "font_weight": "400", "color": "#B0BEC5", "letter_spacing": 0.3, "text_transform": "none" }
      ],
      "default_font": { "family": "Helvetica", "weight": "500", "size": 48, "color": "#FFFFFF", "letter_spacing": 0.5 }
    },
    "box": { "enabled": true, "color": "#1A237E", "opacity": 0.75, "padding": 28, "border_radius": 12, "border_color": null, "border_width": 0 },
    "position": { "anchor": "center", "y_offset": -30, "x_offset": 0 },
    "animation": {
      "entrance_keyframe_id": 1,
      "transform_origin": "center center",
      "per_line": [
        { "keyframe_id": 1, "delay_ms": 0, "transform_origin": null },
        { "keyframe_id": 1, "delay_ms": 300, "transform_origin": null }
      ]
    },
    "decorations": { "divider": { "enable": false }, "emoji_row": { "enable": false }, "badge": { "enable": false } },
    "effects": { "flash": { "enable": false }, "particles": { "enable": false } },
    "overlay": { "gradient_top": { "enable": false }, "gradient_bottom": { "enable": false } },
    "timing": { "display_duration_seconds": 3.0, "delay_before_seconds": 0.5 }
  }',
  NULL,
  1,
  1,
  30
);

-- ─── 4. Cinematic Gold Reveal (cinematic, animated, 3 lines, divider) ───────
INSERT INTO hook_templates (name, description, category, thumbnail_url, style_type, config, user_id, is_active, is_default, sort_order)
VALUES (
  'Cinematic Gold Reveal',
  'Dramatic gold-on-dark hook with slide-up reveal, staggered per-line delays, and a gold divider between lines',
  'cinematic',
  NULL,
  'animated',
  '{
    "text": {
      "lines": [
        { "font_family": "Georgia", "font_size": 58, "font_weight": "700", "color": "#FFD700", "letter_spacing": 1.5, "text_transform": "uppercase" },
        { "font_family": null, "font_size": 46, "font_weight": "500", "color": "#FFF8E1", "letter_spacing": 0.8, "text_transform": "none" },
        { "font_family": null, "font_size": 40, "font_weight": "400", "color": "#FFD700", "letter_spacing": 0.5, "text_transform": "none" }
      ],
      "default_font": { "family": "Georgia", "weight": "700", "size": 50, "color": "#FFD700", "letter_spacing": 1.0 }
    },
    "box": { "enabled": true, "color": "#1A1A1A", "opacity": 0.9, "padding": 32, "border_radius": 4, "border_color": "#FFD700", "border_width": 1 },
    "position": { "anchor": "center", "y_offset": 20, "x_offset": 0 },
    "animation": {
      "entrance_keyframe_id": 3,
      "transform_origin": "bottom center",
      "per_line": [
        { "keyframe_id": 3, "delay_ms": 0, "transform_origin": "bottom center" },
        { "keyframe_id": 3, "delay_ms": 250, "transform_origin": "bottom center" },
        { "keyframe_id": 3, "delay_ms": 500, "transform_origin": "bottom center" }
      ]
    },
    "decorations": { "divider": { "enable": true, "colors": ["#FFD700", "#FFF8E1"], "width": 120, "height": 2, "keyframe_id": 1 }, "emoji_row": { "enable": false }, "badge": { "enable": false } },
    "effects": { "flash": { "enable": false }, "particles": { "enable": false } },
    "overlay": { "gradient_top": { "enable": false }, "gradient_bottom": { "enable": false } },
    "timing": { "display_duration_seconds": 4.0, "delay_before_seconds": 0.5 }
  }',
  NULL,
  1,
  0,
  40
);

-- ─── 5. Slam Down Power (viral, animated, 2 lines) ──────────────────────────
INSERT INTO hook_templates (name, description, category, thumbnail_url, style_type, config, user_id, is_active, is_default, sort_order)
VALUES (
  'Slam Down Power',
  'Heavy-hitting 2-line hook with slam entrance from top — maximum attention-grabbing impact',
  'viral',
  NULL,
  'animated',
  '{
    "text": {
      "lines": [
        { "font_family": "Arial Black", "font_size": 72, "font_weight": "900", "color": "#FF4500", "letter_spacing": 2.0, "text_transform": "uppercase" },
        { "font_family": null, "font_size": 56, "font_weight": "bold", "color": "#FFFFFF", "letter_spacing": 1.0, "text_transform": "uppercase" }
      ],
      "default_font": { "family": "Arial Black", "weight": "900", "size": 64, "color": "#FF4500", "letter_spacing": 1.5 }
    },
    "box": { "enabled": false, "color": "#000000", "opacity": 0.0, "padding": 0, "border_radius": 0, "border_color": null, "border_width": 0 },
    "position": { "anchor": "center", "y_offset": -20, "x_offset": 0 },
    "animation": {
      "entrance_keyframe_id": 8,
      "transform_origin": "top center",
      "per_line": [
        { "keyframe_id": 8, "delay_ms": 0, "transform_origin": "top center" },
        { "keyframe_id": 8, "delay_ms": 200, "transform_origin": "top center" }
      ]
    },
    "decorations": { "divider": { "enable": false }, "emoji_row": { "enable": false }, "badge": { "enable": false } },
    "effects": { "flash": { "enable": false }, "particles": { "enable": false } },
    "overlay": { "gradient_top": { "enable": false }, "gradient_bottom": { "enable": false } },
    "timing": { "display_duration_seconds": 3.0, "delay_before_seconds": 0.2 }
  }',
  NULL,
  1,
  0,
  50
);

-- ─── 6. Playful Bounce Party (playful, animated, 3 lines) ──────────────────
INSERT INTO hook_templates (name, description, category, thumbnail_url, style_type, config, user_id, is_active, is_default, sort_order)
VALUES (
  'Playful Bounce Party',
  'Fun colorful 3-line hook with scale-bounce entrance and staggered reveals — energetic and playful',
  'playful',
  NULL,
  'animated',
  '{
    "text": {
      "lines": [
        { "font_family": "Comic Sans MS", "font_size": 58, "font_weight": "bold", "color": "#FF69B4", "letter_spacing": 0.5, "text_transform": "none" },
        { "font_family": null, "font_size": 50, "font_weight": "bold", "color": "#7C4DFF", "letter_spacing": 0.3, "text_transform": "none" },
        { "font_family": null, "font_size": 44, "font_weight": "600", "color": "#00E5FF", "letter_spacing": 0.3, "text_transform": "none" }
      ],
      "default_font": { "family": "Comic Sans MS", "weight": "bold", "size": 50, "color": "#FF69B4", "letter_spacing": 0.5 }
    },
    "box": { "enabled": true, "color": "#FFFFFF", "opacity": 0.92, "padding": 22, "border_radius": 20, "border_color": "#FF69B4", "border_width": 3 },
    "position": { "anchor": "center", "y_offset": 0, "x_offset": 0 },
    "animation": {
      "entrance_keyframe_id": 2,
      "transform_origin": "center center",
      "per_line": [
        { "keyframe_id": 2, "delay_ms": 0, "transform_origin": null },
        { "keyframe_id": 2, "delay_ms": 180, "transform_origin": null },
        { "keyframe_id": 2, "delay_ms": 360, "transform_origin": null }
      ]
    },
    "decorations": { "divider": { "enable": false }, "emoji_row": { "enable": false }, "badge": { "enable": false } },
    "effects": { "flash": { "enable": false }, "particles": { "enable": false } },
    "overlay": { "gradient_top": { "enable": false }, "gradient_bottom": { "enable": false } },
    "timing": { "display_duration_seconds": 3.5, "delay_before_seconds": 0.3 }
  }',
  NULL,
  1,
  0,
  60
);

-- ─── 7. Minimal Static Hook (professional, static, 2 lines) ────────────────
INSERT INTO hook_templates (name, description, category, thumbnail_url, style_type, config, user_id, is_active, is_default, sort_order)
VALUES (
  'Minimal Static Hook',
  'Clean 2-line static hook with no animation — professional and understated for business content',
  'professional',
  NULL,
  'static',
  '{
    "text": {
      "lines": [
        { "font_family": "Helvetica", "font_size": 50, "font_weight": "600", "color": "#FFFFFF", "letter_spacing": 0.3, "text_transform": "none" },
        { "font_family": null, "font_size": 38, "font_weight": "400", "color": "#90A4AE", "letter_spacing": 0.2, "text_transform": "none" }
      ],
      "default_font": { "family": "Helvetica", "weight": "500", "size": 44, "color": "#FFFFFF", "letter_spacing": 0.3 }
    },
    "box": { "enabled": true, "color": "#263238", "opacity": 0.8, "padding": 24, "border_radius": 8, "border_color": null, "border_width": 0 },
    "position": { "anchor": "center", "y_offset": 0, "x_offset": 0 },
    "animation": {
      "entrance_keyframe_id": null,
      "transform_origin": null,
      "per_line": []
    },
    "decorations": { "divider": { "enable": false }, "emoji_row": { "enable": false }, "badge": { "enable": false } },
    "effects": { "flash": { "enable": false }, "particles": { "enable": false } },
    "overlay": { "gradient_top": { "enable": false }, "gradient_bottom": { "enable": false } },
    "timing": { "display_duration_seconds": 3.0, "delay_before_seconds": 0.5 }
  }',
  NULL,
  1,
  0,
  70
);

-- ─── 8. Simple Dark Static (cinematic, static, 2 lines) ────────────────────
INSERT INTO hook_templates (name, description, category, thumbnail_url, style_type, config, user_id, is_active, is_default, sort_order)
VALUES (
  'Simple Dark Static',
  'Dark cinematic 2-line static hook with serif font — elegant and timeless with no animation',
  'cinematic',
  NULL,
  'static',
  '{
    "text": {
      "lines": [
        { "font_family": "Georgia", "font_size": 54, "font_weight": "700", "color": "#ECEFF1", "letter_spacing": 0.8, "text_transform": "none" },
        { "font_family": null, "font_size": 42, "font_weight": "400", "color": "#78909C", "letter_spacing": 0.5, "text_transform": "none" }
      ],
      "default_font": { "family": "Georgia", "weight": "600", "size": 48, "color": "#ECEFF1", "letter_spacing": 0.6 }
    },
    "box": { "enabled": true, "color": "#121212", "opacity": 0.88, "padding": 26, "border_radius": 4, "border_color": null, "border_width": 0 },
    "position": { "anchor": "center", "y_offset": 30, "x_offset": 0 },
    "animation": {
      "entrance_keyframe_id": null,
      "transform_origin": null,
      "per_line": []
    },
    "decorations": { "divider": { "enable": false }, "emoji_row": { "enable": false }, "badge": { "enable": false } },
    "effects": { "flash": { "enable": false }, "particles": { "enable": false } },
    "overlay": { "gradient_top": { "enable": false }, "gradient_bottom": { "enable": false } },
    "timing": { "display_duration_seconds": 3.5, "delay_before_seconds": 0.5 }
  }',
  NULL,
  1,
  0,
  80
);


-- ============================================================================
-- Seed: Style Compositions
-- Description: Seeds style_compositions with 6 entries pairing caption_templates
--              with hook_templates into ready-to-use style profiles. Entry #1
--              is the default (is_default=1). All are system presets (user_id=NULL).
-- ============================================================================

-- ─── 1. Viral Energy Pack (DEFAULT) — caption "Neon Glow Bounce" + hook "Bold Impact Slide"
INSERT INTO style_compositions (name, description, category, thumbnail_url, caption_template_id, hook_template_id, user_id, is_active, is_default, use_count, sort_order)
VALUES (
  'Viral Energy Pack',
  'High-energy viral style pairing neon glow captions with bold impact slide hook — maximum engagement',
  'viral',
  NULL,
  1,
  1,
  NULL,
  1,
  1,
  0,
  10
);

-- ─── 2. Professional Clean — caption "Minimal White Fade" + hook "Clean Corporate Fade"
INSERT INTO style_compositions (name, description, category, thumbnail_url, caption_template_id, hook_template_id, user_id, is_active, is_default, use_count, sort_order)
VALUES (
  'Professional Clean',
  'Clean professional style pairing minimal white captions with corporate fade hook — suitable for business content',
  'professional',
  NULL,
  3,
  3,
  NULL,
  1,
  0,
  0,
  20
);

-- ─── 3. Cinematic Drama — caption "Cinematic Gold Slide" + hook "Cinematic Gold Reveal"
INSERT INTO style_compositions (name, description, category, thumbnail_url, caption_template_id, hook_template_id, user_id, is_active, is_default, use_count, sort_order)
VALUES (
  'Cinematic Drama',
  'Dramatic cinematic style pairing gold slide captions with gold reveal hook — movie trailer aesthetics',
  'cinematic',
  NULL,
  5,
  4,
  NULL,
  1,
  0,
  0,
  30
);

-- ─── 4. Playful Vibes — caption "Bubblegum Pop" + hook "Playful Bounce Party"
INSERT INTO style_compositions (name, description, category, thumbnail_url, caption_template_id, hook_template_id, user_id, is_active, is_default, use_count, sort_order)
VALUES (
  'Playful Vibes',
  'Fun and energetic style pairing bubblegum pop captions with playful bounce hook — cheerful and engaging',
  'playful',
  NULL,
  7,
  6,
  NULL,
  1,
  0,
  0,
  40
);

-- ─── 5. Bold Slam Combo — caption "Bold Yellow Slam" + hook "Slam Down Power"
INSERT INTO style_compositions (name, description, category, thumbnail_url, caption_template_id, hook_template_id, user_id, is_active, is_default, use_count, sort_order)
VALUES (
  'Bold Slam Combo',
  'Maximum impact viral combo pairing bold yellow slam captions with slam down hook — attention-grabbing',
  'viral',
  NULL,
  2,
  5,
  NULL,
  1,
  0,
  0,
  50
);

-- ─── 6. Understated Elegance — caption "Elegant Serif Quiet" + hook "Simple Dark Static"
INSERT INTO style_compositions (name, description, category, thumbnail_url, caption_template_id, hook_template_id, user_id, is_active, is_default, use_count, sort_order)
VALUES (
  'Understated Elegance',
  'Refined static style pairing elegant serif captions with simple dark hook — timeless and sophisticated',
  'cinematic',
  NULL,
  9,
  8,
  NULL,
  1,
  0,
  0,
  60
);
